CXX := g++
CXXFLAGS := -O2

LLVM_CXXFLAGS := `llvm-config --cxxflags`
LLVM_LDFLAGS := `llvm-config --ldflags --libs`

CLANG_LIBS := \
	-lclangFrontend \
	-lclangSerialization \
	-lclangDriver \
	-lclangTooling \
	-lclangParse \
	-lclangSema \
	-lclangAnalysis \
	-lclangRewriteFrontend \
	-lclangRewriteCore \
	-lclangEdit \
	-lclangAST \
	-lclangLex \
	-lclangBasic

protos: protos.cpp
	$(CXX) $(CXXFLAGS) $(LLVM_CXXFLAGS) $^ \
		$(CLANG_LIBS) $(LLVM_LDFLAGS) -DLLVM_34 -o $@
